### ISSUE TITLE
(Tds.Error) 1 (131): The size (10826) given to the type 'varbinary' exceeds the maximum allowed for any data type (8000).

### ISSUE THREAD

**Issue by sardaukar** [livehelpnow/tds#39]
I'm seeing this error message trying to save large amounts of text to an existing MS SQL database. The current solution works fine, but I'm struggling to do the same with tds.

Here's the schema of the class:

```
schema "somedata" do
    field :analysis, :string
    field :available, :naive_datetime
    field :contents, :string
    field :created, :naive_datetime
    field :heading, :string
    field :onhold, :integer
    field :typecode, :integer
    field :url, :string
    field :userid, :integer

    timestamps(inserted_at: :date, updated_at: false)
  end
```

The only fields that need to be big are `analysis` and `contents`, and they're set to `nvarchar(max)` on the database. 

Is there a way to fix this? I'm starting to think that if the size exceeds 8000 for `VARCHAR` or 4000 for `NVARCHAR`, the driver should not use the real size but "MAX" instead as hinted here -> http://www.sql-server-helper.com/error-messages/msg-131.aspx

**Comment by sardaukar** [comment]
I tried changing the `encode_binary_descriptor(value)` function to:

```elixir
  def encode_binary_descriptor(value) do
    size =
      if value == nil do
        1
      else
        byte_size(value)
      end
    length = if size > 4000, do: "max", else: size
    "varbinary(#{length})"
  end
```

but got this:

```
1 (8016): The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 2 ("@1"): Data type 0xA5 has an invalid data length or metadata length.
```

Why is this being saved as `varbinary` if the fields are set as strings anyway? Thanks for any help.

**Comment by ewitchin** [comment]
Can you try defining the size within your fields in your schema for example:`field :analysis, :string, size: :max`

**Comment by sardaukar** [comment]
@ewitchin just did, same error :(

**Comment by ewitchin** [comment]
Thanks for reporting back. We will look into it!

**Comment by CharlesOkwuagwu** [comment]
This should fix the cases where size >8000

https://github.com/CharlesOkwuagwu/tds/commit/84ae0e37d43322428f362fbea86e769583addce8

Regards.

**Comment by sardaukar** [comment]
@CharlesOkwuagwu I tried your changes to the file, but I got a different error now:

```
1 (214): Procedure expects parameter '@handle' of type 'int'.
```

Is it because your fork is not based on the `ecto-2` branch that I'm using?

**Comment by mjaric** [comment]
> Why is this being saved as varbinary if the fields are set as strings anyway? Thanks for any help.

If varchar or nvarchar is used as an input parameter for stored procedure or prepared statement it is converted into binary to avoid possible SQL injection attacks, it is converted back to nvarchar or varchar in statement with cast. It is safest way to avoid injections. 

I will try to fix this today and I will merge ecto2 branch into master since there is issue with two branches history in tds_ecto repository

**Comment by sardaukar** [comment]
thanks @mjaric !

**Comment by sardaukar** [comment]
@mjaric will that fix the "attempted to insert a stale struct" error too? or is that a separate issue?

**Comment by mjaric** [comment]
it should be different issue. This happens when migration is run and the last query is insert into dbo.schema_migrations table. It fails since return bad. Let me just merge everyhting into master and then we will see if it fails. Since I think I solved it. Probably mix.lock is not updated in tds_ecto repo.

I will let you know when it is ready.

**Comment by sardaukar** [comment]
Thanks again @mjaric !

**Comment by mjaric** [comment]
Could you now try with master branch instead. point tds_ecto to

**Comment by sardaukar** [comment]
@mjaric do you mean `{:tds_ecto, github: "livehelpnow/tds_ecto", branch: "master"}` with `tds_ecto` instead of `tds` ?

**Comment by mjaric** [comment]
yes it is :tds_ecto dependency I'm refering to

**Comment by sardaukar** [comment]
I just tried - same error message with `varbinary` exceeding 8000.

**Comment by sardaukar** [comment]
To make sure I'm not shooting my own foot, here are my full deps:

```
defp deps do
    [
      {:phoenix, "~> 1.3.0"},
      {:phoenix_pubsub, "~> 1.0"},
      {:phoenix_ecto, "~> 3.2"},
      {:phoenix_html, "~> 2.10"},
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:gettext, "~> 0.11"},
      {:cowboy, "~> 1.0"},
      {:tds_ecto, github: "livehelpnow/tds_ecto", branch: "master"},
      {:ex_debug_toolbar, "~> 0.3.0"},
      {:envy, "~> 1.1.1"},
      {:credo, "~> 0.8", only: [:dev, :test], runtime: false},
      {:httpoison, "~> 0.13"},
      {:xml_builder, "~> 0.1.1"},
      {:timex, "~> 3.1"},
      {:exml, "~> 0.1.1"},
    ]
  end
```

**Comment by mjaric** [comment]
Hi, I found the issue so this should be fixed in latest master. Please do `mix deps.update tds`. Or if you are using tds_ecto it should be `mix desp.update tds_ecto`

**Comment by sardaukar** [comment]
@mjaric I'm still seeing error 131 after updating. Here's my relevant part of `mix deps`:

```
* tds 0.6.0-alpha (https://github.com/livehelpnow/tds.git) (mix)
  locked at 844cd4c (branch: master)
  ok
* tds_ecto 2.0.0-alpha (https://github.com/livehelpnow/tds_ecto.git) (mix)
  locked at 7e02500 (branch: master)
  ok
```

Do I need to do something special to update? Some other branch?

**Comment by sardaukar** [comment]
OK, I've `mix deps.update tds` separately from `tds_ecto` and now I see:

```
1 (8016): The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 2 ("@1"): Data type 0xA5 has an invalid data length or metadata length.
```

:|
